[project]
name = "lab-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.1.0",
    "matplotlib>=3.10.3",
    "setuptools>=80.4.0",
]
